networks:
  nextcloud-net:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
    networks:
      - nextcloud-net

  app:
    build: build/
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./data:/var/www/html/data
      - ./opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=1024m
      - NVIDIA_VISIBLE_DEVICES=all
      - OVERWRITEPROTOCOL=https
    networks:
      - nextcloud-net
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - nextcloud-net

  web:
    image: nginx:latest
    restart: always
    ports:
      - 4080:4080
    volumes:
      - ./mime.types:/etc/nginx/mime.types:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
      - ./proxy.conf:/etc/nginx/conf.d/include/proxy.conf
    volumes_from:
      - app
    networks:
      - nextcloud-net
